[package]
name = "bevy_mod_scripting"
version = "0.1.0"
authors = ["Maksymilian Mozolewski <makspl17@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Bevy plugin for enabling scripting"
repository = "https://github.com/makspll/bevy_scripting"
homepage = "https://github.com/makspll/bevy_scripting"
keywords = ["bevy", "gamedev", "scripting", "lua"]
categories = ["game-development"]
readme = "../readme.md"
rust-version = "1.61.0"

[lib]
name = "bevy_mod_scripting"
path = "src/lib.rs"


[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d" }
rlua = "0.19.2"
rhai = { version = "1.7.0", features = ["sync"] }
anyhow = "1.0.57"
beau_collector = "0.2.1"
once_cell = "1.10.0"
bevy_event_priority = { path = "../bevy_event_priority" }
num = "0.4.0"
phf = {version = "0.10.1", features= ["macros"] }
thiserror = "1.0.31"
lazy_static = "1.4.0"
paste = "1.0.7"
parking_lot = "0.12.1"
ouroboros = "0.15.0"
bevy_mod_scripting_derive = {path = "../bevy_mod_scripting_derive"}

[dev-dependencies]
bevy_console = { git = "https://github.com/OnlyGraphs/bevy-console" }
bevy_asset_loader = {git = "https://github.com/NiklasEi/bevy_asset_loader", features = ["dynamic_assets"]}
rand = "0.8.5"
serde = "1.0.137"

# For those that have not specified anything:
[patch."https://github.com/bevyengine/bevy"]
bevy = { git = "https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d" }

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d"}

# needs bevy 0.8 support from console
# [[example]]
# name = "console_integration_lua"
# path = "examples/console_integration_lua.rs"


# [[example]]
# name = "console_integration_rhai"
# path = "examples/console_integration_rhai.rs"

[[example]]
name = "complex_game_loop"
path = "examples/complex_game_loop.rs"


[[example]]
name = "event_recipients"
path = "examples/event_recipients.rs"


[[example]]
name = "custom_user_data"
path = "examples/custom_user_data.rs"