on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    defaults:
      run:
        working-directory: ./bevy_scripting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        working-directory: ./bevy_scripting
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          working-directory: ./bevy_scripting
          command: check

  test:
    name: Test Suite
    defaults:
      run:
        working-directory: ./bevy_scripting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          working-directory: ./bevy_scripting
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          working-directory: ./bevy_scripting
          command: test

  fmt:
    name: Rustfmt
    defaults:
      run:
        working-directory: ./bevy_scripting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          working-directory: ./bevy_scripting
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          working-directory: ./bevy_scripting
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    defaults:
      run:
        working-directory: ./bevy_scripting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          working-directory: ./bevy_scripting
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          working-directory: ./bevy_scripting
          command: clippy
          args: -- -D warnings