on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      manual_tag:
        description: 'release tag'
        required: true
        default: 'undefined'
        type: string

name: Documentation Generation

jobs:
  lua:
    name: Lua Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2.2.0
      - run: cargo run --features=lua54,lua_script_api lua
      - run: ls
      - run: ls assets/
      - run: ls assets/scripts/
      - run: ls assets/scripts/doc/
      - run: mv ./assets/scripts/doc/BevyAPI /BevyAPI
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.LUA_DOCUMENTATION_SSH_KEY }}
        with:
          source-directory: '/BevyAPI'
          destination-github-username: 'makspll'
          destination-repository-name: 'bevy_mod_scripting_lua'
          user-email: makspl17@gmail.com
          target-branch: main
          target-directory: ${{ github.event.release.tag_name || inputs.manual_tag }}
